### ISSUE TITLE
password reset dialog: button stays deactivated

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1054]

**Comment by haraldschilly** [comment]
should be solved by 21bba712f6b9f2643c17761588 -- please check

**Comment by williamstein** [comment]
Horribly not solved right now.  Here's the console.log when testing -- both the logging and it completely not working...

[7.86s Δ 0.08s] wstein@sagemat true
smc-8283559….js?8283559…:11 [7.99s Δ 0.13s] wstein@sagemath true
smc-8283559….js?8283559…:11 [8.1s Δ 0.11s] wstein@sagemath. false
smc-8283559….js?8283559…:11 [8.18s Δ 0.08s] wstein@sagemath.c true
smc-8283559….js?8283559…:11 [8.27s Δ 0.09s] wstein@sagemath.co true
smc-8283559….js?8283559…:237 Uncaught TypeError: this.is_valid_email is not a function
