### ISSUE TITLE
Install qepcad on cloud.sagemath.com

### ISSUE THREAD

**Issue by jondo** [sagemathinc/smc#163]
Recently we have got [a new qepcad package](http://trac.sagemath.org/ticket/10224). Couuld you please install it on cloud.sagemath.com?

We need it for our students to clean up the solution of e.g.
```python
maxima_calculus("domain: real")
dnf = solve(abs((x-1)/(x-5))<1/3,x)
```

(This should give `[[-1 < x, x < 2]]` instead of `[[x == 1], [1 < x, x < 2], [-1 < x, x < 1]]`.)

The cleanup works like this:
```python
qf = apply(qepcad_formula.or_, map(qepcad_formula.and_, dnf)) # reformat the solution
qepcad(qf, vars='(x)') # simplify
```

**Comment by williamstein** [comment]
Done -- please confirm.

**Comment by jondo** [comment]
I still see `RuntimeError: unable to start QEPCAD`, see [this file](https://cloud.sagemath.com/projects/0ac0ee4d-8031-40a3-a0e0-fa56ddb1c167/files/2015-10-13-163157.sagews).

**Comment by williamstein** [comment]
There were some permission issues.  Things should now be fixed.

**Comment by jondo** [comment]
Yes, It works now. Great, thank you!
